# Example .worktree.yml Configuration
# Copy this to your project root and customize for your needs

# Project definitions
projects:
  # Example: Backend service
  backend:
    dir: backend                              # Directory relative to project root
    main_branch: main                         # Main branch name
    start_command: "docker-compose up -d"     # Start services ({instance} placeholder)
    migration_command: "npm run migrate"      # Run migrations (optional)
    post_command: "npm run seed"              # Run after start (fixtures, seed data)
    claude_working_dir: true                  # Set as Claude's working directory

  # Example: Frontend app
  frontend:
    dir: frontend
    main_branch: main
    start_command: "PORT={port} npm start"    # Use {port} for dynamic ports
    # No migrations or post_command needed

  # Example: Microservice
  api:
    dir: services/api
    main_branch: develop
    start_command: "go run main.go --port 808{instance}"
    migration_command: "make migrate INSTANCE={instance}"

  # Example: Worker/Queue
  worker:
    dir: worker
    main_branch: main
    start_command: "python worker.py --instance {instance}"
    post_command: "python seed_jobs.py"

# Preset configurations
presets:
  # Full-stack development
  fullstack:
    projects: [backend, frontend]
    description: "Backend + Frontend"

  # Backend only
  backend:
    projects: [backend]
    description: "Backend API only"

  # All services
  all:
    projects: [backend, frontend, api, worker]
    description: "All services"

# Default preset
default_preset: fullstack

# Maximum instances (0-N)
max_instances: 5

# Auto-run migrations
auto_migrations: true

# Auto-run post-commands (fixtures, seed)
auto_fixtures: true

# Port/Service display configuration
# Customize what services are shown after setup
ports:
  # Frontend example
  frontend:
    name: "Frontend"
    url: "http://localhost:{port}"
    port: "3000 + {instance}"    # Expression: base + instance

  # Backend API
  backend:
    name: "Backend API"
    url: "http://localhost:{port}"
    port: "8080 + {instance}"

  # API documentation (Swagger, ReDoc, etc.)
  docs:
    name: "API Docs"
    url: "http://localhost:{port}/docs"
    port: "8080 + {instance}"

  # Database examples
  postgres:
    name: "PostgreSQL"
    url: "localhost:{port}"
    port: "5432 + {instance}"

  mysql:
    name: "MySQL"
    url: "localhost:{port}"
    port: "3306 + {instance}"

  mongo:
    name: "MongoDB"
    url: "mongodb://localhost:{port}"
    port: "27017 + {instance}"

  redis:
    name: "Redis"
    url: "redis://localhost:{port}"
    port: "6379 + {instance}"

  # Message queues
  rabbitmq:
    name: "RabbitMQ"
    url: "http://localhost:{port}"
    port: "15672 + {instance}"    # Management UI

  kafka:
    name: "Kafka"
    url: "localhost:{port}"
    port: "9092 + {instance}"

  # Monitoring & Debugging
  grafana:
    name: "Grafana"
    url: "http://localhost:{port}"
    port: "3001 + {instance}"

  prometheus:
    name: "Prometheus"
    url: "http://localhost:{port}"
    port: "9090 + {instance}"

  jaeger:
    name: "Jaeger"
    url: "http://localhost:{port}"
    port: "16686 + {instance}"

  # Development tools
  mailcatcher:
    name: "Mail"
    url: "http://localhost:{port}"
    port: "1080 + {instance}"

  adminer:
    name: "Adminer"
    url: "http://localhost:{port}"
    port: "8080 + {instance}"

  # AWS LocalStack
  localstack:
    name: "LocalStack"
    url: "http://localhost:{port}"
    port: "4566 + {instance}"

  # gRPC services
  grpc:
    name: "gRPC"
    url: "localhost:{port}"
    port: "50051 + {instance}"

# Notes:
# - {instance} is replaced with the instance number (0, 1, 2, etc.)
# - {port} is calculated from the port expression
# - Port expressions support: "base + {instance}" format
# - Only configured ports are displayed (remove unused services)
# - Services are shown in the order defined here
