# Fullstack Docker Example Configuration
#
# This example demonstrates:
# - Frontend (React/Vue) + Backend (Go/Node) with Docker Compose
# - Dynamic port allocation (${APP_PORT:-8080} pattern)
# - Multi-repo structure with shared .claude/ directory
# - Symlinks for shared configurations
#
# This is the MOST COMMON setup for teams using Docker.
#
# Copy this to your project root and customize for your stack.

project_name: "myproject"
hostname: localhost

projects:
  backend:
    executor: docker
    dir: backend
    main_branch: main
    start_command: "docker compose up -d"
    start_post_command: "docker compose exec -T api make migrate"  # Optional: run migrations after start
    claude_working_dir: true

  frontend:
    executor: docker
    dir: frontend
    main_branch: main
    start_command: "docker compose up -d"

presets:
  fullstack:
    projects: [backend, frontend]
    description: "Full application (backend + frontend)"

  backend:
    projects: [backend]
    description: "Backend only"

  frontend:
    projects: [frontend]
    description: "Frontend only"

default_preset: fullstack

env_variables:
  APP_PORT:
    name: "Backend API"
    url: "http://{host}:{port}"
    port: "8080"
    env: "APP_PORT"
    range: [8080, 8180]

  FE_PORT:
    name: "Frontend"
    url: "http://{host}:{port}"
    port: "3000"
    env: "FE_PORT"
    range: [3000, 3100]

  POSTGRES_PORT:
    name: "PostgreSQL"
    url: "{host}:{port}"
    port: "5432"
    env: "POSTGRES_PORT"
    range: [5432, 5532]

  MAILPIT_PORT:
    name: "Mailpit UI"
    url: "http://{host}:{port}"
    port: "8025"
    env: "MAILPIT_PORT"
    range: [8025, 8125]

  # String template that references other env vars
  REACT_APP_API_BASE_URL:
    name: "API Base URL (for frontend)"
    url: "{value}"
    value: "http://{host}:{APP_PORT}"
    env: "REACT_APP_API_BASE_URL"

# Symlinks - Share files across all worktrees
symlinks:
  - path: .claude
    description: "Shared Claude config (skills, hooks)"

# Generated files - Create these files in each worktree
generated_files:
  - path: "{project}/.env.worktree"
    content: |
      # Generated by worktree-manager for {project}
      # Instance: {instance} | Feature: {feature}
      # DO NOT EDIT - This file is regenerated on worktree start

      APP_PORT={APP_PORT}
      FE_PORT={FE_PORT}
      POSTGRES_PORT={POSTGRES_PORT}
      MAILPIT_PORT={MAILPIT_PORT}
      REACT_APP_API_BASE_URL={REACT_APP_API_BASE_URL}
