# Minimal Example - Single Backend Project
#
# Perfect for: Solo developers, testing the tool, API-only projects
#
# This is the SIMPLEST possible worktree-manager setup.
# One project, one port, no Docker - just the basics.

project_name: "myapi"
hostname: localhost

projects:
  backend:
    executor: process  # No Docker needed!
    dir: backend
    main_branch: main
    start_command: "go run main.go"  # Or: npm start, python app.py, etc.

presets:
  backend:
    projects: [backend]

default_preset: backend

env_variables:
  APP_PORT:
    name: "Backend API"
    url: "http://{host}:{port}"
    port: "8080"
    env: "APP_PORT"
    range: [8080, 8180]  # Supports 100 instances (8080-8179)
